// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SqlServer.Management.IntegrationServices")]
[assembly: AssemblyProductAttribute("SqlServer.Management.IntegrationServices")]
[assembly: AssemblyDescriptionAttribute("SQL Server Integration Services management library for executing and working with SSIS packages")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
