// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SqlServer.Management.IntegrationServices.WebApi")]
[assembly: AssemblyProductAttribute("SqlServer.Management.IntegrationServices")]
[assembly: AssemblyDescriptionAttribute("SQL Server Integration Services management library for executing and working with SSIS packages located in the integration services catalog.")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
